addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: efc7f540-a7c7-4d58-b25c-b3c454f179cd
after_success: [./df-build.sh]
language: java
notifications: {}
# Modified by Insights Service at 2016-04-27 14:46:42.808570
